source "http://rubygems.org"
gem "rake"
gem "cucumber", ">0.0"
gem "rspec", ">0.0"
gem "watir-webdriver", "~>0.6.1"
gem "watir-webdriver-performance", "~>0.1.3.1"
gem "watir-page-helper", ">0.0"
gem "cuporter", ">0.0"
gem "headless", ">0.0"
gem "yard-cucumber"
gem "rdiscount"
gem "selenium-webdriver", "~>2.24.0"
