source "http://rubygems.org"
gem "rake"
gem "cucumber", ">0.0"
gem "rspec", ">0.0"
gem "watir-webdriver"
gem "watir-webdriver-performance", ">0.1.2"
gem "cuporter", ">0.0"
gem "headless", ">0.0"
gem "yard-cucumber"
gem "rdiscount"
gem "mysql"
gem "launchy"
