Given /^QBot is running$/ do
  visit BookingPage
end

When /^QBot is surfing a webpage$/ do
  on NextLinkPage do |page| 

#para subir modificaciones por ftp a amazon, utilizar la carpeta /tmp
#una vez alli, reubicar a la carpeta que sea necesaria
#si ha de ser manipulada, es posible que se necesiten cambios de permisos
#utilizar por ejemplo: sudo chmod ugo+rw launcheslog.xml
#
#
#para ver espacio de disco en uso 
#df -h
#
#para crear estructura de directorios de golpe (ojo con no dejar espacios entre las llaves):
#mkdir -p a/{b1,b2} 
#
#contar ficheros dentro de una carpeta y subcarpetas:
#find . -type f | wc -l
#
#crear un fichero tipo bat:
# - crear un fichero con cualquier extension
# - añadirle los comandos
# - guardarlo y cambiarlo a tipo ejecutable con: chmod 755 <nombrefichero>
# - lanzar ejecucion con bash <nombrefichero>

    #idLaunch = page.getLaunch
    #idLaunch='00000006'

    #idLaunch = page.getLaunch
    #page.launch idLaunch,'VENERE_HotelList.Buenos Aires', 'http://www.venere.com/esff/argentina/buenos-aires/#p|1;f:o|venere_ranking-t|C-z|all_areas-r|r6-c|all_rate', '//*[@id="next" and @class="next"]', '//*[@id="paging_bottom"]', '//*[@id="loading" and @style!="display: none;"]'
    #page.launch idLaunch,'VENERE_HotelList.Tegucigalpa', 'http://www.venere.com/es/honduras/tegucigalpa/#p|1;f:o|venere_ranking-t|C-z|-r|r6-c|all_rate', '//*[@id="next" and @class="next"]', '//*[@id="paging_bottom"]', '//*[@id="loading" and @style!="display: none;"]'

    #idLaunchTRIVAGO = page.getLaunch
    #idLaunchEXPEDIA = page.getLaunch
    #idLaunchVENERE = page.getLaunch
    
    #idLaunch = "00000058"
    idLaunch = page.getLaunch
    
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.A_CORUNA', 'http://www.hotelscombined.com/ES/City/A_Coruna_1.htm#languageCode=ES&currencyCode=EUR&destination=city:A_Coruna&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1368&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.A_CORUNA', 'http://www.hotelsearch.com/hotels/europa/espana/galicia/a-coruna/la-coruna/763246.es.html?page=1&sort=survey#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.A_CORUNA', 'http://www.quehoteles.com/hoteles-en-a-coruna-4C15P109D141Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.ALBACETE', 'http://www.hotelscombined.com/Place.aspx?languageCode=ES&currencyCode=EUR&destination=city:Albacete&radius=15km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=912&open=3,2,1,4,7,6&mapstate=contracted#languageCode=ES&currencyCode=EUR&destination=city:Albacete&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.ALBACETE', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-la-mancha/albacete/751648.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.ALBACETE', 'http://www.quehoteles.com/hoteles-en-albacete-4C15P111D152Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.ALICANTE', 'http://www.hotelscombined.com/ES/City/Alicante_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Alicante&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1368&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.ALICANTE', 'http://www.hotelsearch.com/hotels/europa/espana/comunidad-valenciana/alicante/752101.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.ALICANTE', 'http://www.quehoteles.com/hoteles-en-alicante-4C15P112D155Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.ALMERIA', 'http://www.hotelscombined.com/ES/City/Almeria_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Almeria&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.ALMERIA', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/almeria/752212.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.ALMERIA', 'http://www.quehoteles.com/hoteles-en-almeria-4C15P903D1963Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.AVILA', 'http://www.hotelscombined.com/ES/City/Avila_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Avila&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.AVILA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/avila/12691140.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.AVILA', 'http://www.quehoteles.com/hoteles-en-avila-4C15P114D203Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.BADAJOZ', 'http://www.hotelscombined.com/ES/City/Badajoz_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Badajoz&radius=2km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1026&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.BADAJOZ', 'http://www.hotelsearch.com/hotels/europa/espana/extremadura/badajoz/753442.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.BADAJOZ', 'http://www.quehoteles.com/hoteles-en-badajoz-4C15P115D207Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.BALEARES', 'http://www.hotelsearch.com/hotels/europa/espana/islas-baleares/baleares/12602088.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.BILBAO', 'http://www.hotelscombined.com/ES/City/Bilbao_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Bilbao&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.BILBAO', 'http://www.hotelsearch.com/hotels/europa/espana/pais-vasco/vizcaya/bilbao/754542.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.BILBAO', 'http://www.quehoteles.com/hoteles-en-bilbao-4C15P176D781Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.BURGOS', 'http://www.hotelscombined.com/ES/City/Burgos_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Burgos&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1026&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.BURGOS', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/burgos/755078.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.BURGOS', 'http://www.quehoteles.com/hoteles-en-burgos-4C15P118D231Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.CACERES', 'http://www.hotelscombined.com/ES/City/Caceres_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Caceres&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=799&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.CACERES', 'http://www.hotelsearch.com/hotels/europa/espana/extremadura/caceres/755379.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.CACERES', 'http://www.quehoteles.com/hoteles-en-caceres-4C15P119D238Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.CADIZ', 'http://www.hotelscombined.com/ES/City/Cadiz_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Cadiz&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1141&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.CADIZ', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/cadiz/755404.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.CADIZ', 'http://www.quehoteles.com/hoteles-en-cadiz-4C15P120D246Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.CANARIAS', 'http://www.hotelsearch.com/hotels/europa/espana/islas-canarias/12578031.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.CASTELLON_DE_LA_PLANA', 'http://www.hotelscombined.com/ES/City/Castellon_de_la_Plana_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Castellon_de_la_Plana&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1141&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.CASTELLON_DE_LA_PLANA', 'http://www.hotelsearch.com/hotels/europa/espana/comunidad-valenciana/castellon/castellon-de-la-plana/756804.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.CASTELLON_DE_LA_PLANA', 'http://www.quehoteles.com/hoteles-en-castellon-4C15P122D277Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.CIUDAD_REAL', 'http://www.hotelscombined.com/ES/City/Ciudad_Real_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Ciudad_Real&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=799&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.CIUDAD_REAL', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-la-mancha/ciudad-real/757692.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.CIUDAD_REAL', 'http://www.quehoteles.com/hoteles-en-ciudad-real-4C15P124D280Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.CORDOBA', 'http://www.hotelscombined.com/ES/City/Cordoba_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Cordoba&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1026&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.CORDOBA', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/cordoba/758007.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.CORDOBA', 'http://www.quehoteles.com/hoteles-en-cordoba-4C15P125D284Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.CUENCA', 'http://www.hotelscombined.com/ES/City/Cuenca_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Cuenca&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.CUENCA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-la-mancha/cuenca/758467.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.CUENCA', 'http://www.quehoteles.com/hoteles-en-cuenca-4C15P134D383Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.ELCHE', 'http://www.hotelscombined.com/City/Elche_1.htm', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.ELCHE', 'http://www.hotelsearch.com/hotels/europa/espana/comunidad-valenciana/alicante/elche/23388441.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.ELCHE', 'http://www.quehoteles.com/hoteles-en-elche-4C15P112D165Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.GIJON', 'http://www.hotelscombined.com/ES/City/Gijon_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Gijon&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.GIJON', 'http://www.hotelsearch.com/hotels/europa/espana/principado-de-asturias/asturias/gijon/761570.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.GIJON', 'http://www.quehoteles.com/hoteles-en-gijon-4C15P113D187Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.GIRONA', 'http://www.hotelscombined.com/ES/City/Girona_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Girona&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1027&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.GIRONA', 'http://www.hotelsearch.com/hotels/europa/espana/cataluna/gerona/girona/761600.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.GIRONA', 'http://www.quehoteles.com/hoteles-en-gerona-4C15P137D400Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.GRANADA', 'http://www.hotelscombined.com/ES/City/Granada_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Granada&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1368&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.GRANADA', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/granada/761766.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.GRANADA', 'http://www.quehoteles.com/hoteles-en-granada-4C15P139D430Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.GUADALAJARA', 'http://www.hotelscombined.com/ES/City/Guadalajara_Spain_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Guadalajara_Spain&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1027&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.GUADALAJARA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-la-mancha/guadalajara/761869.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.GUADALAJARA', 'http://www.quehoteles.com/hoteles-en-guadalajara-4C15P140D443Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.HOSPITALET', 'http://www.hotelscombined.com/ES/City/LHospitalet_de_Llobregat_1.htm', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.HOSPITALET', 'http://www.hotelsearch.com/hotels/europa/espana/cataluna/barcelona/l-hospitalet-de-llobregat/12693480.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.HOSPITALET', 'http://www.quehoteles.com/hoteles-en-hospitalet-de-llobregat-4C15P116D1489Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.HUELVA', 'http://www.hotelscombined.com/ES/City/Huelva_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Huelva&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.HUELVA', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/huelva/762399.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.HUELVA', 'http://www.quehoteles.com/hoteles-en-huelva-4C15P142D452Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.HUESCA', 'http://www.hotelscombined.com/ES/City/Huesca_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Huesca&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.HUESCA', 'http://www.hotelsearch.com/hotels/europa/espana/aragon/huesca/762456.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.HUESCA', 'http://www.quehoteles.com/hoteles-en-huesca-4C15P143D454Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.JAEN', 'http://www.hotelscombined.com/ES/City/Jaen_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Jaen&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.JAEN', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/jaen/762761.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.JAEN', 'http://www.quehoteles.com/hoteles-en-jaen-4C15P145D486Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.JEREZ_DE_LA_FRONTERA', 'http://www.hotelscombined.com/ES/City/Jerez_de_la_Frontera_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Jerez_de_la_Frontera&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1482&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.JEREZ_DE_LA_FRONTERA', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/cadiz/jerez-de-la-frontera/762833.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.JEREZ_DE_LA_FRONTERA', 'http://www.quehoteles.com/hoteles-en-jerez-de-la-frontera-4C15P120D251Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.LEON', 'http://www.hotelscombined.com/ES/City/Leon_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Leon&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=799&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.LEON', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/leon/765099.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.LEON', 'http://www.quehoteles.com/hoteles-en-leon-4C15P151D522Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.LERIDA', 'http://www.hotelscombined.com/ES/City/Lleida_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Lleida&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1027&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.LERIDA', 'http://www.hotelsearch.com/hotels/europa/espana/cataluna/lerida/765112.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.LERIDA', 'http://www.quehoteles.com/hoteles-en-lleida-4C15P152D526Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.LOGRONO', 'http://www.hotelscombined.com/ES/City/Logrono_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Logrono&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1369&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.LOGRONO', 'http://www.hotelsearch.com/hotels/europa/espana/la-rioja/logrono/765455.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.LOGRONO', 'http://www.quehoteles.com/hoteles-en-logrono-4C15P149D505Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.LUGO', 'http://www.hotelscombined.com/ES/City/Lugo_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Lugo&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.LUGO', 'http://www.hotelsearch.com/hotels/europa/espana/galicia/lugo/766207.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.LUGO', 'http://www.quehoteles.com/hoteles-en-lugo-4C15P153D528Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.MADRID', 'http://www.hotelscombined.com/ES/City/Madrid_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Madrid&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=2166&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.MADRID', 'http://www.hotelsearch.com/hotels/europa/espana/comunidad-de-madrid/madrid/766273.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.MADRID', 'http://www.quehoteles.com/hoteles-en-madrid-4C15P154D545Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.MALAGA', 'http://www.hotelscombined.com/ES/City/Malaga_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Malaga&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1254&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.MALAGA', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/malaga/766356.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.MALAGA', 'http://www.quehoteles.com/hoteles-en-malaga-4C15P155D562Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.MERIDA', 'http://www.hotelscombined.com/ES/City/Merida_Spain_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Merida_Spain&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1141&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.MERIDA', 'http://www.hotelsearch.com/hotels/europa/espana/extremadura/badajoz/merida/12694402.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.MERIDA', 'http://www.quehoteles.com/hoteles-en-merida-4C15P115D208Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.MURCIA', 'http://www.hotelscombined.com/Place.aspx?languageCode=ES&currencyCode=EUR&destination=city:Murcia&radius=10km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,7,3&view=hc_sr_summary&scroll=1368&open=3,2,1,4,7,6&mapstate=contracted#languageCode=ES&currencyCode=EUR&destination=city:Murcia&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,7,3&view=hc_sr_summary&scroll=1&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.MURCIA', 'http://www.hotelsearch.com/hotels/europa/espana/region-de-murcia/murcia/768026.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.MURCIA', 'http://www.quehoteles.com/hoteles-en-murcia-4C15P159D663Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.OVIEDO', 'http://www.hotelscombined.com/Place.aspx?languageCode=ES&currencyCode=EUR&destination=city:Oviedo&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted#languageCode=ES&currencyCode=EUR&destination=city:Oviedo&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.OVIEDO', 'http://www.hotelsearch.com/hotels/europa/espana/principado-de-asturias/asturias/oviedo/769112.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.OVIEDO', 'http://www.quehoteles.com/hoteles-en-oviedo-4C15P113D196Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.PALENCIA', 'http://www.hotelscombined.com/ES/City/Palencia_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Palencia&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1141&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.PALENCIA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/palencia/769278.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.PALENCIA', 'http://www.quehoteles.com/hoteles-en-palencia-4C15P162D676Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.PAMPLONA', 'http://www.hotelscombined.com/ES/City/Pamplona_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Pamplona&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.PAMPLONA', 'http://www.hotelsearch.com/hotels/europa/espana/comunidad-foral-de-navarra/navarra/pamplona/769330.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.PAMPLONA', 'http://www.quehoteles.com/hoteles-en-pamplona-4C15P160D670Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.PONTEVEDRA', 'http://www.hotelscombined.com/ES/City/Pontevedra_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Pontevedra&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.PONTEVEDRA', 'http://www.hotelsearch.com/hotels/europa/espana/galicia/pontevedra/770472.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.PONTEVEDRA', 'http://www.quehoteles.com/hoteles-en-pontevedra-4C15P165D695Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.SALAMANCA', 'http://www.hotelscombined.com/Place.aspx?languageCode=ES&currencyCode=EUR&destination=city:Salamanca&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=863&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.SALAMANCA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/salamanca/772416.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.SALAMANCA', 'http://www.quehoteles.com/hoteles-en-salamanca-4C15P166D705Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.SAN_SEBASTIAN', 'http://www.hotelscombined.com/ES/City/San_Sebastian_1.htm#languageCode=ES&currencyCode=EUR&destination=city:San_Sebastian&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1254&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.SAN_SEBASTIAN', 'http://www.hotelsearch.com/hotels/europa/espana/pais-vasco/guipuzcoa/st-sebastien/donostia-san-sebastian/773418.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.SAN_SEBASTIAN', 'http://www.quehoteles.com/hoteles-en-san-sebastian-4C15P141D448Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.SANTANDER', 'http://www.hotelscombined.com/ES/City/Santander_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Santander&radius=2km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1140&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.SANTANDER', 'http://www.hotelsearch.com/hotels/europa/espana/cantabria/santander/773964.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.SANTANDER', 'http://www.quehoteles.com/hoteles-en-santander-4C15P121D267Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.SANTIAGO_DE_COMPOSTELA', 'http://www.hotelscombined.com/ES/City/Santiago_de_Compostela_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Santiago_de_Compostela&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1368&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.SANTIAGO_DE_COMPOSTELA', 'http://www.hotelsearch.com/hotels/europa/espana/galicia/a-coruna/santiago-de-compostela/773998.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.SANTIAGO_DE_COMPOSTELA', 'http://www.quehoteles.com/hoteles-en-santiago-de-compostela-4C15P109D148Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.SEGOVIA', 'http://www.hotelscombined.com/ES/City/Segovia_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Segovia&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=912&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.SEGOVIA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/segovia/774288.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.SEGOVIA', 'http://www.quehoteles.com/hoteles-en-segovia-4C15P168D731Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.SEVILLA', 'http://www.hotelscombined.com/ES/City/Seville_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Seville&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1596&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.SEVILLA', 'http://www.hotelsearch.com/hotels/europa/espana/andalucia/sevilla/774508.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.SEVILLA', 'http://www.quehoteles.com/hoteles-en-sevilla-4C15P169D737Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.SORIA', 'http://www.hotelscombined.com/ES/City/Soria_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Soria&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.SORIA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/soria/774837.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.SORIA', 'http://www.quehoteles.com/hoteles-en-soria-4C15P170D741Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.TARRAGONA', 'http://www.hotelscombined.com/ES/City/Tarragona_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Tarragona&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1254&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.TARRAGONA', 'http://www.hotelsearch.com/hotels/europa/espana/cataluna/tarragona/775246.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.TARRAGONA', 'http://www.quehoteles.com/hoteles-en-tarragona-4C15P167D726Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.TERUEL', 'http://www.hotelscombined.com/ES/City/Teruel_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Teruel&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.TERUEL', 'http://www.hotelsearch.com/hotels/europa/espana/aragon/teruel/775399.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.TERUEL', 'http://www.quehoteles.com/hoteles-en-teruel-4C15P172D771Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.TOLEDO', 'http://www.hotelscombined.com/ES/City/Toledo_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Toledo&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=1254&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.TOLEDO', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-la-mancha/toledo/775524.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.TOLEDO', 'http://www.quehoteles.com/hoteles-en-toledo-4C15P173D775Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.VALENCIA', 'http://www.hotelscombined.com/ES/City/Valencia_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Valencia&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1482&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.VALENCIA', 'http://www.hotelsearch.com/hotels/europa/espana/comunidad-valenciana/valencia/776688.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.VALENCIA', 'http://www.quehoteles.com/hoteles-en-valencia-4C15P174D776Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.VALLADOLID', 'http://www.hotelscombined.com/ES/City/Valladolid_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Valladolid&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0&view=hc_sr_summary&scroll=913&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.VALLADOLID', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/valladolid/776745.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.VALLADOLID', 'http://www.quehoteles.com/hoteles-en-valladolid-4C15P175D780Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.VIGO', 'http://www.hotelscombined.com/ES/City/Vigo_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Vigo&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1368&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.VIGO', 'http://www.hotelsearch.com/hotels/europa/espana/galicia/pontevedra/vigo/777341.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.VIGO', 'http://www.quehoteles.com/hoteles-en-vigo-4C15P165D702Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.VITORIA', 'http://www.hotelscombined.com/ES/City/Vitoria_Gasteiz_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Vitoria_Gasteiz&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=1027&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.VITORIA', 'http://www.hotelsearch.com/hotels/europa/espana/pais-vasco/alava/vitoria-gasteiz/vitoria/778899.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.VITORIA', 'http://www.quehoteles.com/hoteles-en-vitoria-gasteiz-4C15P110D151Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.ZAMORA', 'http://www.hotelscombined.com/ES/City/Zamora_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Zamora&radius=5km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&view=hc_sr_summary&scroll=1&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.ZAMORA', 'http://www.hotelsearch.com/hotels/europa/espana/castilla-y-leon/zamora/779045.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.ZAMORA', 'http://www.quehoteles.com/hoteles-en-zamora-4C15P177D786Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''
    page.launch idLaunch,'HOTELSCOMBINED_HotelList.ZARAGOZA', 'http://www.hotelscombined.com/ES/City/Zaragoza_1.htm#languageCode=ES&currencyCode=EUR&destination=city:Zaragoza&radius=0km&Rooms=1&adults_1=1&pageSize=25&pageIndex=0&sort=Popularity-desc&showSoldOut=true&propertyType=0,3&view=hc_sr_summary&scroll=216&open=3,2,1,4,7,6&mapstate=contracted', '//*[@id="pagination"]//a[@class="hc_sr_paging_next" and not(.././preceding-sibling::li[1]/@class)]', '//*[@id="hc_r_ft"]', ''
    page.launch idLaunch,'HOTELSEARCH_HotelList.ZARAGOZA', 'http://www.hotelsearch.com/hotels/europa/espana/aragon/zaragoza/779063.es.html#listView', '//a[@class="next_page"]', '//*[@id="footer"]', ''
    page.launch idLaunch,'QUEHOTELES_HotelList.ZARAGOZA', 'http://www.quehoteles.com/hoteles-en-zaragoza-4C15P178D790Z.htm', '(//a[@class="sig" and ./text()="Siguiente"])[1]', '//span[@class="bottom"]', ''


  end
  
end

Then /^QBot should get a snapshot$/ do

end
