Given /^QBot is running$/ do
  visit BookingPage
end

When /^QBot is surfing a webpage$/ do
  on NextLinkPage do |page| 

#para subir modificaciones por ftp a amazon, utilizar la carpeta /tmp
#una vez alli, reubicar a la carpeta que sea necesaria
#si ha de ser manipulada, es posible que se necesiten cambios de permisos
#utilizar por ejemplo: sudo chmod ugo+rw launcheslog.xml
#
#
#para ver espacio de disco en uso 
#df -h
#
#para crear estructura de directorios de golpe (ojo con no dejar espacios entre las llaves):
#mkdir -p a/{b1,b2} 
#
#contar ficheros dentro de una carpeta y subcarpetas:
#find . -type f | wc -l
#
#crear un fichero tipo bat:
# - crear un fichero con cualquier extension
# - añadirle los comandos
# - guardarlo y cambiarlo a tipo ejecutable con: chmod 755 <nombrefichero>
# - lanzar ejecucion con bash <nombrefichero>

    #idLaunch = page.getLaunch
    #idLaunch='00000006'

    #idLaunch = page.getLaunch
    #page.launch idLaunch,'VENERE_HotelList.Buenos Aires', 'http://www.venere.com/esff/argentina/buenos-aires/#p|1;f:o|venere_ranking-t|C-z|all_areas-r|r6-c|all_rate', '//*[@id="next" and @class="next"]', '//*[@id="paging_bottom"]', '//*[@id="loading" and @style!="display: none;"]'
    #page.launch idLaunch,'VENERE_HotelList.Tegucigalpa', 'http://www.venere.com/es/honduras/tegucigalpa/#p|1;f:o|venere_ranking-t|C-z|-r|r6-c|all_rate', '//*[@id="next" and @class="next"]', '//*[@id="paging_bottom"]', '//*[@id="loading" and @style!="display: none;"]'

    #idLaunchTRIVAGO = page.getLaunch
    #idLaunchEXPEDIA = page.getLaunch
    #idLaunchVENERE = page.getLaunch
    
    #idLaunch = "000000040"
    idLaunch = page.getLaunch
    
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d237159-Reviews-Confortel_Almirante-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d239537-Reviews-Hotel_Rey_Don_Jaime_I-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1026843-Reviews-Castell_de_l_Oliver-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d2268168-Reviews-Residencia_Universitaria_San_Agustin-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d228483-Reviews-Catalonia_Park_Putxet_Hotel-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d234569-Reviews-Gran_Hotel_Barcino-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1799581-Reviews-Gothic_Downtown_1-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d652748-Reviews-Hotel_Ruta_de_Francia-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d652750-Reviews-Turo_de_Lhome-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d579801-Reviews-Rege_Apart_Apartments-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651523-Reviews-Hostal_Ballestero-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1202241-Reviews-Laberint-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#15', 'http://www.tripadvisor.es/Hotel_Review-g187497-d652543-Reviews-Hotel_l_Orenta-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1931412-Reviews-Ciutadella_Park_Apartments-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1754263-Reviews-B_B_Trilobite_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d609868-Reviews-Hostal_River-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1569152-Reviews-Sagrada_Familia_Home-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1195997-Reviews-Sol_Apartments-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d678843-Reviews-Agua_Alegre-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651635-Reviews-Hotel_Bruc-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1647663-Reviews-L_Ou_de_Reig-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d652551-Reviews-Hotel_Parets_Els_Pins-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d489100-Reviews-Lyon_Hotel-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1204611-Reviews-Apt_Gran_Central_Inn-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d260794-Reviews-Pension_Europa-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1227151-Reviews-Barceloneta_Atlantida-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1211777-Reviews-City_Park_Hotel_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d231512-Reviews-Hotel_Ciutat_de_Mollet-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1125694-Reviews-Harbour_Palace_2-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651516-Reviews-Aparthotel_Acces-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d568843-Reviews-Sant_Cugat-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1212774-Reviews-Campanile_Hotel_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1211628-Reviews-Pere_III_Hotel_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d484842-Reviews-Barcelona_Escape_Apartments-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d304310-Reviews-Sansi_Diputacio_Hotel-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1204581-Reviews-Barcelona_Nextdoor_Apartments-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d666299-Reviews-Hesperia_Sarria-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1211626-Reviews-Ciutat_de_Igualada_Hotel_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1828347-Reviews-Casa_Amalia-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1204657-Reviews-Avimer_32-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1205759-Reviews-Bailen-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d234576-Reviews-Apartamentos_Mur_Mar-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#16', 'http://www.tripadvisor.es/Hotel_Review-g187497-d232783-Reviews-Santa_Marta_Hotel-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651517-Reviews-Hotel_Amilcar-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d286161-Reviews-Pension_Dali-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1143982-Reviews-Badal_Hotel-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d636152-Reviews-BCN_Houses_Daily_Apartments_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d652742-Reviews-Pension_Lesseps-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1491872-Reviews-AAE_Orleans_Hotel_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d661969-Reviews-Apartamentos_Bahia-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1210392-Reviews-AS_Bellaterra_Hotel_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1638414-Reviews-Calabria_House-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1589987-Reviews-Alberg_Gaudi-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1217389-Reviews-Medena-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d652752-Reviews-Vila_de_Caldes-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1146187-Reviews-Pension_Picasso-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1205285-Reviews-Ramblas_Liceu-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d949915-Reviews-La_Rambla_dels_Caputxins-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1222750-Reviews-Apartments_Visit_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d208596-Reviews-Hotel_Granvia-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1217515-Reviews-AB_Arena-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651519-Reviews-Ana_Maria_Hotel-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1204572-Reviews-Apt_Granados_Guest_Rooms-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1217190-Reviews-AR_Barcelona_Calvet-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1217191-Reviews-AR_Barcelona_Casals-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1202248-Reviews-Avenir-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1227115-Reviews-Avimer_31-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1177701-Reviews-Barcelona_Apartments_Plaza_Espana-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d535290-Reviews-Barcelona_Classic-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1214441-Reviews-Bruc_Apartment-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651528-Reviews-Cal_Peraire-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651609-Reviews-Cal_Rale-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#17', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1379600-Reviews-Coliseum_Apartment-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1205453-Reviews-Diamante-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651627-Reviews-Europedralbes_Hotel-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1219883-Reviews-Feel_Good_Sagrada_Familia-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1196970-Reviews-Feramblas_Apartment-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1227122-Reviews-Gaudi_II-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1227055-Reviews-Gothic_Residential-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d582238-Reviews-HLG_Airprat-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d651526-Reviews-Hotel_Betres-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d573470-Reviews-Hotel_Carlos-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d4014393-Reviews-Hotel_Catalonia_Passeig_de_Gracia-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d652548-Reviews-Hotel_Mar_Eden-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d619688-Reviews-Hotel_Peru_Playa-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1211630-Reviews-Hotel_Services_Apartments_City_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d3964699-Reviews-Hotel_Vueling_BCN_by_Hc-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1194869-Reviews-Modernista-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1204602-Reviews-Nou_Rambla_Loft_Apartments-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1227072-Reviews-Plaza_de_las_Ollas-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1185677-Reviews-Rentingflats-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1473017-Reviews-Residencia_Guri-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1204654-Reviews-Suite_Dreams_Apts-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1217108-Reviews-El_Vilar-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1546464-Reviews-Born_Picasso_A-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1509420-Reviews-Red_Apartment-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BARCELONA#18', 'http://www.tripadvisor.es/Hotel_Review-g187497-d1412362-Reviews-Sant_Gervasi_Apartment_Barcelona-Barcelona_Catalonia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264356-Reviews-Riviera_Beachotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264358-Reviews-Villa_Venecia_Hotel_Boutique-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264361-Reviews-Servigroup_Castilla-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1208751-Reviews-Villa_Del_Mar_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264380-Reviews-Corona_del_Mar_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1228462-Reviews-Servigroup_Nereo-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264494-Reviews-Sandos_Monaco_Beach_Hotel_Spa-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264359-Reviews-Servigroup_Venus-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1211632-Reviews-Servigroup_Calypso-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d287291-Reviews-Terralta_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1142016-Reviews-Servigroup_Rialto-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d277590-Reviews-Hotel_La_Cala-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314988-Reviews-Benimar_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264500-Reviews-Hotel_Perla_Residencia-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d3384066-Reviews-Royal_Queens-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d238667-Reviews-Hotel_Don_Pancho-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d289780-Reviews-Hotel_Centro_Mar-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d498141-Reviews-Hotel_Royal-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d289396-Reviews-Magic_Aqua_Rock_Gardens-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264383-Reviews-Servigroup_Diplomatic-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d498199-Reviews-Hotel_Mediterraneo_Benidorm-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264419-Reviews-Hotel_Helios_Benidorm-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264497-Reviews-Servigroup_Orange_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d281133-Reviews-RH_Hotel_Victoria-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d601295-Reviews-Hotel_Deloix_Aqua_Center-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264511-Reviews-Servigroup_Pueblo_Benidorm-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264521-Reviews-Servigroup_Torre_Dorada-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314991-Reviews-Flamingo_Oasis-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1010477-Reviews-Hotel_Riudor-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#01', 'http://www.tripadvisor.es/Hotel_Review-g187525-d273137-Reviews-Hotel_Nadal-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264510-Reviews-Hotel_RH_Princesa-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1059356-Reviews-Pension_La_Orozca-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264506-Reviews-Presidente_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314997-Reviews-Picasso_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d606477-Reviews-Melia_Villaitana-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314993-Reviews-Hotel_Levante_Club_Spa-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264041-Reviews-Hotel_Rio_Park-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264044-Reviews-Hotel_Regente-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d238650-Reviews-Hotel_Brisa-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530143-Reviews-Hotel_Madeira_Centro-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d231534-Reviews-Sol_Costablanca-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d313586-Reviews-Hotel_Benikaktus-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264349-Reviews-Hotel_Ambassador_Playa_I_II-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264357-Reviews-Hotel_Magic_Villa_de_Benidorm-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264384-Reviews-Hotel_Magic_Fenicia-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d231532-Reviews-Melia_Benidorm-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1109754-Reviews-Barcelo_Asia_Gardens_Hotel_Thai_Spa-Benidorm_Costa_Blanca_Alicante_Province_Valencian_.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d231533-Reviews-Sol_Pelicanos_Ocas-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d3152696-Reviews-Flash_Hotel_Benidorm-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314990-Reviews-La_Era_Park_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264345-Reviews-Alpha_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d276082-Reviews-Hotel_Mar_Blau-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530135-Reviews-Hotel_Vista_Oro-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264502-Reviews-Hotel_Benidorm_Plaza-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264355-Reviews-Beni_Beach_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264381-Reviews-Magic_Cristal_Park_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d273117-Reviews-Hotel_Agir-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d273123-Reviews-Carlos_I_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530179-Reviews-Hotel_Montemar-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#02', 'http://www.tripadvisor.es/Hotel_Review-g187525-d605975-Reviews-Hotel_Bilbaino-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264509-Reviews-Prince_Park_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1370959-Reviews-Hotel_Caballo_de_Oro-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507715-Reviews-Les_Dunes_Comodoro_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264504-Reviews-Poseidon_Playa_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d754183-Reviews-Mayra_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1161402-Reviews-Poseidon_Complex-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d609661-Reviews-The_Queens_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264350-Reviews-Hotel_Avenida-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264374-Reviews-Bristol_Park_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264409-Reviews-Dynastic_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d259949-Reviews-Hotel_Marina-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264416-Reviews-Marconfort_Flamingo_Benidorm_Aparthotel-Benidorm_Costa_Blanca_Alicante_Province_Valenci.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264382-Reviews-Los_Dalmatas_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264047-Reviews-Palm_Beach_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d273119-Reviews-Benidorm_Centre_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507743-Reviews-Halley_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d506935-Reviews-Marconi_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507741-Reviews-Hotel_Joya-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d508229-Reviews-Belroy_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314996-Reviews-Palm_Court_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264514-Reviews-Hotel_Rosamar-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d238644-Reviews-Hotel_Cimbel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264505-Reviews-Poseidon_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507841-Reviews-Benilux_Park_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1022652-Reviews-Maria_Cristina_Beach-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d567130-Reviews-Magic_Tropicana_Suites-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314989-Reviews-Don_Salva_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530192-Reviews-Hotel_Melina-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530138-Reviews-Tanit-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#03', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535574-Reviews-Rinconada_Real-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507717-Reviews-Camposol-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264231-Reviews-Gran_Hotel_Bali-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530175-Reviews-Mont_Park-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1483050-Reviews-Primavera_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d508231-Reviews-Hotel_Brasil-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d238649-Reviews-RH_Hotel_Canfali-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d578293-Reviews-Avenida_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530140-Reviews-Apartamentos_Torre_San_Diego-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1109419-Reviews-La_Estacion-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264410-Reviews-Europa_Center_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535578-Reviews-Hotel_Tropic-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530202-Reviews-Hotel_Iris-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507733-Reviews-Milord_s_Suites-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1104409-Reviews-Villa_Marina_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1420046-Reviews-Hotel_Colon-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530150-Reviews-Santa_Margarita-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535549-Reviews-Gemelos_II-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507742-Reviews-Jaime_I-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507752-Reviews-Estudios_Benidorm-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d482972-Reviews-Los_Alamos_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264423-Reviews-Olympus_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264413-Reviews-Fiesta_Park_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530239-Reviews-Acapulco-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264417-Reviews-Gala_Placidia_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530162-Reviews-Hotel_Oasis_Plaza-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d529097-Reviews-Hotel_el_Palmeral-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530152-Reviews-Paraiso_Centro-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d506653-Reviews-Hotel_RH_Internacional-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264412-Reviews-El_Faro_Aparthotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#04', 'http://www.tripadvisor.es/Hotel_Review-g187525-d638647-Reviews-Hotel_La_Santa_Faz-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d506670-Reviews-Hotel_RH_Sol-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264499-Reviews-Payma_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264351-Reviews-Bali_Ie_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d531033-Reviews-Hotel_Andalucia-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530879-Reviews-Apartments_Michelangelo-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530139-Reviews-Sol_y_Sombra-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530170-Reviews-Hotel_Mayna-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507757-Reviews-El_Trebol-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530207-Reviews-Las_Vegas-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535557-Reviews-Mar_Y_Montana-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264376-Reviews-Cabana_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264344-Reviews-Agua_Azul_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1221229-Reviews-Fleming_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d941795-Reviews-Esmeralda_Hotel_Art-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264420-Reviews-Mediterraneo_Sur_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1498061-Reviews-Los_Arcos-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530229-Reviews-Costa_Blanca-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1165052-Reviews-Robert_Palas_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1213833-Reviews-Bermudas_Hotel_Benidorm_Costa_Blanca-Benidorm_Costa_Blanca_Alicante_Province_Valencian.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530240-Reviews-Alameda_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d529100-Reviews-Hotel_Paca-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264507-Reviews-Primavera_Dos_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1204750-Reviews-La_Santa_Faz-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d315000-Reviews-Vacanza_Mayve_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530236-Reviews-Calas_Marina_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535572-Reviews-Residencial_Club_Europeo-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d583810-Reviews-Don_Cesar_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507716-Reviews-Voramar_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535521-Reviews-Hotel_Teremar-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#05', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507722-Reviews-Torre_Ipanema-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507719-Reviews-Gemelos_XV-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d585995-Reviews-Hotel_Jamaica-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264378-Reviews-Cadiz_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530431-Reviews-Apartamentos_Coral_Beach-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d277584-Reviews-Atenea_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507844-Reviews-Apartahotel_Bermudas-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264508-Reviews-Primavera_Park_Apartments_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Count.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1006028-Reviews-Flamingo_Sunplaces_Apartamentos-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Coun.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d273126-Reviews-Condal_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507728-Reviews-San_Francisco_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535554-Reviews-Hotel_Golden-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264513-Reviews-Rosaire_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1151955-Reviews-Cervantes-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1151536-Reviews-Hotel_Rambla-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d580547-Reviews-Mirador_Studios-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264353-Reviews-Bali_Hotel-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d632190-Reviews-Mar_Bella-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535523-Reviews-San_Jaime_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314999-Reviews-Tropicmar_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530238-Reviews-Alonis-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1142168-Reviews-Apartamentos_Vacanza-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530217-Reviews-Aptos_Paraiso_Florida-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535541-Reviews-Coblanca_29-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1508428-Reviews-Coblanca_XXII_y_Coblanca_35-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530235-Reviews-Complejo_Vacacional_Lope_De_Vega-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Coun.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535545-Reviews-Espranoleto-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507753-Reviews-Estocolmo-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535548-Reviews-Europa_Sur-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535553-Reviews-Gemelos_12-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#06', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535551-Reviews-Gemelos_5-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535552-Reviews-Gemelos_8-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d239193-Reviews-Gran_Hotel_Delfin-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507846-Reviews-Hotel_Bonanza-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1495194-Reviews-Hotel_Don_Jose-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d507746-Reviews-Kennedy_I_II-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535543-Reviews-El_Marino-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264490-Reviews-Mar_Pinos_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1379679-Reviews-Michelangello_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d292871-Reviews-Montecarlo_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535561-Reviews-Monver_8_10-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d314995-Reviews-Ocana_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535565-Reviews-Oferta_Benidorm_2-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535566-Reviews-Parque_Europa-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d264501-Reviews-Plata_Apartments-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535567-Reviews-Principado_Arena-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535568-Reviews-Principado_Centro-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d535569-Reviews-Principado_Europa-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1211001-Reviews-Sierra_Cortina_Resort_Hotel_Benidorm_Costa_Blanca-Benidorm_Costa_Blanca_Alicante_Provi.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d530199-Reviews-Varios_1a_Linea-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.BENIDORM#07', 'http://www.tripadvisor.es/Hotel_Review-g187525-d1419354-Reviews-La_Costera-Benidorm_Costa_Blanca_Alicante_Province_Valencian_Country.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d541333-Reviews-La_Villa_Marbella_Charming_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d652757-Reviews-The_Marbella_Heights_Boutique_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d779413-Reviews-Hotel_Claude_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d229493-Reviews-Marriott_s_Marbella_Beach_Resort-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d234284-Reviews-Marbella_Club_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d504351-Reviews-La_Morada_Mas_Hermosa_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1160871-Reviews-Vincci_Seleccion_Estrella_del_Mar-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d565230-Reviews-Hotel_Apartamentos_Puerta_de_Aduares-Marbella_Costa_del_Sol_Province_of_Malaga_Andaluci.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d206952-Reviews-Iberostar_Marbella_Coral_Beach-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d228506-Reviews-Hotel_Puente_Romano-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d228477-Reviews-Melia_La_Quinta_Golf_Spa_Resort-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d228580-Reviews-Hotel_Guadalmina_Spa_Golf_Resort-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d228635-Reviews-Hotel_Fuerte_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d228534-Reviews-Gran_Melia_Don_Pepe-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d238809-Reviews-Princesa_Playa_Hotel_Apartamentos-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d232724-Reviews-Hotel_Los_Monteros-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d228606-Reviews-Don_Carlos_Leisure_Resort_Spa-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d507885-Reviews-Vasari_Vacation_Resort-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1085197-Reviews-El_Presidente_Apartments-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d230657-Reviews-Hotel_Fuerte_Miramar-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d305573-Reviews-Villa_Padierna_Palace_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d568934-Reviews-Senator_Marbella_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d482437-Reviews-Melia_Marbella_Banus-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d275963-Reviews-NH_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d231652-Reviews-Hotel_Lima_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1151650-Reviews-Rio_Real_Golf_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d567180-Reviews-Hostal_Berlin-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d508274-Reviews-Aparthotel_Puerto_Azul_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d252892-Reviews-H10_Andalucia_Plaza-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#01', 'http://www.tripadvisor.es/Hotel_Review-g187439-d289966-Reviews-Hotel_NH_San_Pedro-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d621013-Reviews-Hostal_Paco-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d487082-Reviews-Barcelo_Marbella_Golf_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d529065-Reviews-Central-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d263844-Reviews-Marbella_Playa_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d314563-Reviews-Diverhotel_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d236984-Reviews-Hotel_San_Cristobal-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d951112-Reviews-Hotel_Don_Alfredo-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d3225267-Reviews-Guadalpin_Suites-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d232723-Reviews-Pyr_Marbella_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d275962-Reviews-NH_Alanda-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d530967-Reviews-Senorio_de_Aloha-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d610840-Reviews-Gran_Hotel_Guadalpin_Banus-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d238663-Reviews-El_Rodeo-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d274974-Reviews-Gran_Hotel_Guadalpin_Marbella_Spa-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d206965-Reviews-Incosol_Hotel_and_Spa-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d239171-Reviews-Hostal_El_Castillo-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d272704-Reviews-El_Faro-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d654786-Reviews-Marina_Mariola_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d606417-Reviews-Hotel_Linda_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d259428-Reviews-BlueBay_Banus-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1795423-Reviews-Nouvelles_Frontieres_Hotel_Club_Costa_del_Sol-Marbella_Costa_del_Sol_Province_of_Malag.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d529066-Reviews-Hotel_Baviera-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d2090829-Reviews-Albergue_Inturjoven_Marbella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d264996-Reviews-Park_Plaza_Suites-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d239173-Reviews-Marbella_Inn-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d238822-Reviews-Las_Chapas_Palacio_del_Sol-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1196405-Reviews-The_Hostal_del_Pilar-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1170057-Reviews-Atlantic_Club_Reserva_De_Marbella_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Anda.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d228555-Reviews-Don_Miguel_Golf_And_Sport_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#02', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1368380-Reviews-Buchinger_Clinic-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1423008-Reviews-Aptos_Mediterraneo-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d2187745-Reviews-Hotel_San_Pedro_de_al_cantara-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d254940-Reviews-Las_Terrazas_de_Banus-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1227255-Reviews-Hostal_Los_Pacos-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d264989-Reviews-Alcotan_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d292121-Reviews-Royal_Marbella_Playa-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d264994-Reviews-Jardines_Del_Mar_Apartments-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d236983-Reviews-Hotel_Artola_Golf-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1223670-Reviews-El_Paraiso_Hotel-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d265619-Reviews-Alanda_Carib_Playa-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d264991-Reviews-Arqueros_Apartments-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d277126-Reviews-Azalea_Beach-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d238660-Reviews-Hostal_Munich-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d305575-Reviews-Santa_Maria_Golf_Suites-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d508272-Reviews-Costa_Estrella-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d3741825-Reviews-Hotel_Monarque_El_Rodeo-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d1198130-Reviews-Las_Lolas_3_bedroom_apartment-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d593440-Reviews-Las_Lomas_de_Sierra_Blanca-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
    page.launchTAReviews idLaunch, 'TAIndivMob.MARBELLA#03', 'http://www.tripadvisor.es/Hotel_Review-g187439-d264995-Reviews-Mairena_Apartments-Marbella_Costa_del_Sol_Province_of_Malaga_Andalucia.html'
     
  end
  
end

Then /^QBot should get a snapshot$/ do

end
