Given /^QBot is running$/ do
  visit BookingPage
end

When /^QBot is surfing a webpage$/ do
  on NextLinkPage do |page| 

#para subir modificaciones por ftp a amazon, utilizar la carpeta /tmp
#una vez alli, reubicar a la carpeta que sea necesaria
#si ha de ser manipulada, es posible que se necesiten cambios de permisos
#utilizar por ejemplo: sudo chmod ugo+rw launcheslog.xml


    #idLaunch = page.getLaunch
    #idLaunch='00000006'

    #idLaunch = page.getLaunch
    #page.launch idLaunch,'VENERE_HotelList.Buenos Aires', 'http://www.venere.com/es/argentina/buenos-aires/#p|1;f:o|venere_ranking-t|C-z|all_areas-r|r6-c|all_rate', '//*[@id="next" and @class="next"]', '//*[@id="paging_bottom"]', '//*[@id="loading" and @style!="display: none;"]'
    #page.launch idLaunch,'VENERE_HotelList.Tegucigalpa', 'http://www.venere.com/es/honduras/tegucigalpa/#p|1;f:o|venere_ranking-t|C-z|-r|r6-c|all_rate', '//*[@id="next" and @class="next"]', '//*[@id="paging_bottom"]', '//*[@id="loading" and @style!="display: none;"]'

    idLaunchTRIVAGO = page.getLaunch
    idLaunchEXPEDIA = page.getLaunch
    idLaunchVENERE = page.getLaunch
    
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2568.REPESCA01.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-954227', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1462.Sao Paulo', 'http://www.venere.com/es/holiday-inn/san-pablo/holiday-inn-parque-anhembi/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1883.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Fasano-Hotel-Sao-Paulo.h967131.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2569.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1405942', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2570.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104841', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1884.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Exec-21st-Century.h1807366.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1463.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-slaviero-executive-jardins/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2571.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104894', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1885.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Hotel-NEWciti-Sao-Paulo.h4319233.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2572.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-153721', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1464.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hampton-park-residence/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2573.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-478406', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1886.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Exec-Faria-Lima.h691431.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2574.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-520996', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1887.Sao Paulo', 'http://www.expedia.com/Mairinque-Hotels-Confraria-Colonial-Hotel-Boutique.h4441141.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2575.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-935745', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1465.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-riema-paulista-classic/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1888.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Classic-La-Residence.h82839.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2576.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1052156', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2577.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1475973', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1889.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Hampton-Park.h444445.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1466.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-blue-tree-towers-berrini/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2578.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1501449', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1890.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Travel-Inn-Conde-Luciano-Higienopolis.h542131.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2579.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1689673', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1467.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-bella-augusta/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2580.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1754073', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1891.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Bella-Augusta-Residence.h542138.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2581.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104510', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1892.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-P-International.h691432.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2582.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104876', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1468.Sao Paulo', 'http://www.venere.com/es/holiday-inn/san-pablo/holiday-inn-express-sumare-ave/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2583.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-477881', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1893.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Slaviero-Slim-Congonhas.h4513254.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2584.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-478401', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1469.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-luz-plaza/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1894.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Classic-Opera.h526969.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2585.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-479206', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2586.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-521011', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1895.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-InterCity-Premium-Ibirapuera.h1001116.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1470.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/sao-paulo-inn/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2587.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-888515', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1896.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Regent-Park-Hotel.h444626.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2588.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1329032', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1897.Sao Paulo', 'http://www.expedia.com/Guarulhos-Hotels-Bristol-Dobly-International-Hotel.h794182.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2589.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1335383', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1471.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-sao-paulo/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2590.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1554627', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1898.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Dan.h2966420.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2591.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1580781', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1472.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-etoile-george-itaim/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1899.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Tsue-The-Palace-Flat.h4453227.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2592.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1689667', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2593.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1769447', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1900.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Blue-Tree-Premium-Berrini.h330217.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1473.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-pergamon/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2594.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1824903', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1901.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Howard-Johnson-Hotel-Sao-Paulo.h1047824.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2595.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1942111', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2596.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1959481', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1902.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Exec-The-Special.h1807354.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1474.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-bourbon-ibirapuera/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2597.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2019647', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1903.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-155-Hotel.h3910718.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2598.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2045853', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1475.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-porto-palace/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1904.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Sao-Paulo-Inn.h26670.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2599.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2144384', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2600.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2235056', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1905.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Travel-Inn-Ritz.h49351.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1476.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/travel-inn-braston-sao-paulo/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2601.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104659', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1906.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Hotel-Trianon-Paulista.h430561.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2602.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104768', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2603.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104818', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1477.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/transamerica-la-residence/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1907.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Travel-Inn-Braston-Sao-Paulo.h16740.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2604.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104921', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1908.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Prime-The-World.h598693.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2605.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104925', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1478.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-slaviero-executive-guarulhos/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2606.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-104935', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1909.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Lorena-Hotel-Internacional.h1807707.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2607.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-107190', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1910.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Travel-Inn-Braston-Augusta.h5064.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1479.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/regent-park-hotel/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2608.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-107651', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2609.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-150387', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1911.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Tsue-Bienal-Flat.h48059.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2610.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-153725', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1480.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/higienopolis-hotel-suites/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1912.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Pergamon.h471262.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2611.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-478946', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1913.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Hotel-Transamerica-Sao-Paulo.h4655276.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2612.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-521006', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1481.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-executive-congonhas/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2613.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-655721', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1914.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Rojas-All-Suites-Hotel.h174199.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2614.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-655726', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1915.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Slaviero-Executive-Jardins.h545769.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1482.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/dobly-international-hotel/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2615.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-655736', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2616.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-929573', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1916.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Green-Place-Flat.h978489.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2617.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-973493', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1483.Sao Paulo', 'http://www.venere.com/es/golden-tulip/san-pablo/hotel-belas-artes/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1917.Sao Paulo', 'http://www.expedia.com/Guarulhos-Hotels-Slaviero-Executive-Guarulhos.h979693.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2618.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1036140', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2619.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1036258', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1918.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Luz-Plaza.h1665288.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1484.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-executive-chacara-santo-antonio/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2620.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1052520', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1919.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-InterCity-Premium-Nacoes-Unidas.h486464.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2621.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1052528', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1485.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-tsue-bienal-flat/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1920.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Etoile-George-V-Itaim.h1678800.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2622.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1084406', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2623.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1144774', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1921.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Carillon-Plaza-Hotel.h4498643.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2624.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1323175', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1486.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-trianon-paulista/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1922.Sao Paulo', 'http://www.expedia.com/Penha-Hotels-Plumas-Motel.h4724263.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2625.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1500317', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2626.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1580761', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1923.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-InterCity-Premium-Berrini.h971583.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1487.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-hotel/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2627.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1630627', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1924.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Riema-Paulista-Classic.h1807714.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2628.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1647719', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1488.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-etoile-george-jardins/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2629.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1648501', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1925.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Hotel-Moncloa.h4613704.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2630.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1664967', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1926.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Executive-Chacara-Santo-Antonio.h1807406.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2631.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1668359', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1489.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-tsue-the-palace-flat/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2632.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1674411', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1927.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Executive-Congonhas.h1807713.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2633.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1707427', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1928.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Terra-Nobre-Plaza-Hotel.h4039890.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1490.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-prime-the-world/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2634.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1707667', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1929.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Classic-Victoria.h82899.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2635.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1710959', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1491.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-classic-higienopolis/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2636.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1714535', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1930.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Exec-The-Advance.h691436.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2637.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1721575', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1931.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Etoile-George-V-Jardins.h1678789.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2638.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1754083', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1492.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-slaviero-slim-congonhas/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2639.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1754087', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1932.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Augusta-Park-Suite-Hotel.h526858.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2640.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1754097', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1493.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-classic/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1933.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Riema-Saint-Charbel-Suites-Life.h1807419.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2641.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1882841', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2642.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1890749', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1934.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Amaralina-Hotel.h3469407.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1494.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-newciti/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2643.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1893267', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1935.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Porto-Palace-Hotel.h3958060.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2644.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1911031', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1936.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Higienopolis-Hotel-Suites.h4593853.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2645.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1931275', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1495.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-riema-saint-charbel/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2646.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-1963011', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1937.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Clas-Higienopolis.h82863.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2647.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2001147', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1496.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-intercity-premium-ibirapuera/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1938.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Executive-Perdizes.h1807364.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2648.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2021081', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2649.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2043405', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1939.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Matsubara-Hotel.h1807598.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1497.Sao Paulo', 'http://www.venere.com/es/pensiones/san-pablo/pension-green-place-flat/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2650.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2086760', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1940.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-The-Universe-Flat.h539460.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2651.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2155714', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2652.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2175458', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1941.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Prime-Paradise.h1807368.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1498.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-300186/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2653.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2175522', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1942.Sao Paulo', 'http://www.expedia.com/Osasco-Hotels-Best-Western-Osasco.h1172166.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2654.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2176842', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1499.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/grand-plaza-hotel/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2655.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2176844', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1943.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Columbia.h1272703.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2656.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2178232', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1944.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Transamerica-Exec-The-First.h4548862.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1500.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-transamerica-executive/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2657.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2178824', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1945.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Real-Castilha.h1175211.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2658.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2180438', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2659.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2234832', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1501.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/matsubara-hotel/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1946.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Fortune-Residence-And-Executiv.h48060.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2660.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2240280', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1947.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Travel-Inn-Ibirapuera.h915915.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2661.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2248616', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1502.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/lorena-hotel-internacional/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2662.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2249294', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1948.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Hotel-Metropolitano.h1397721.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2663.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2258696', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1949.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-H3-Hotel-Paulista.h4559971.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1503.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-intercity-premium-berrini/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2664.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2271678', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2665.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2278052', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1950.Sao Paulo', 'http://www.expedia.com/Sao-Paulo-Hotels-Feller-Avenida-Paulista-Hotel.h1210615.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2666.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2314900', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1504.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/amaralina-hotel/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1951.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Clarion-Hotel-Real-Tegucigalpa.h328468.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2667.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2324764', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1952.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Tegucigalpa-Marriott-Hotel.h1080711.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2668.Sao Paulo', 'http://www.trivago.es/lugar-12/hotel/hotel-2324768', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1505.Sao Paulo', 'http://www.venere.com/es/hoteles/san-pablo/hotel-intercity-premium-nacoes-unidas/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2669.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-314001', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1953.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-InterContinental-Real-Tegucigalpa.h551899.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2670.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-1760853', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1954.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Hotel-And-Casino-Excelsior.h461336.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1506.Sao Paulo', 'http://www.venere.com/es/golden-tulip/san-pablo/hotel-interative/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2671.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-952377', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2672.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-100592', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1955.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Hotel-Portal-Del-Angel.h897083.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2673.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-313941', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1507.Tegucigalpa', 'http://www.venere.com/es/intercontinental-hotels/tegucigalpa/hotel-intercontinental-real-tegucigalpa/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1956.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Honduras-Maya-Hotel.h199423.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2674.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-313956', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2675.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-408931', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1957.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Hotel-Plaza-Del-General.h526722.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1508.Tegucigalpa', 'http://www.venere.com/es/clarion-hotels/tegucigalpa/hotel-clarion-tegucigalpa/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2676.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-313991', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1958.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Hotel-Plaza-San-Martin.h994823.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2677.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-408946', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''
    page.launch idLaunchEXPEDIA,'EXPEDIA_HotelCard.IdList1959.Tegucigalpa', 'http://www.expedia.com/Tegucigalpa-Hotels-Minister-Business-Hotel.h4970947.Hotel-Information', '', '//*[@id="reviewsSummaryBox"]', ''
    page.launch idLaunchVENERE,'VENERE_HotelCard.IdList1509.Tegucigalpa', 'http://www.venere.com/es/marriott-hotels/tegucigalpa/hotel-marriott-tegucigalpa/', '', '//*[@id="avg_guest_review"]', ''
    page.launch idLaunchTRIVAGO,'TRIVAGO_HotelCard.IdList2678.Tegucigalpa', 'http://www.trivago.es/lugar-12/hotel/hotel-2077274', '', '//*[@id="item_main_details"]/div[@class="details item"]', ''

  end
  
end

Then /^QBot should get a snapshot$/ do

end
